name: ESLint
description: Run ESLint
runs:
  using: "composite"
  steps:
    - name: Install deps
      shell: bash
      run: |
           pnpm install --frozen-lockfile --ignore-scripts
           pnpm run lint
